/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Fri, Jan 13, 2017                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :SH7085                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/



#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif


void HardwareSetup(void)
{
/*
  SCI0.SCSMR.BYTE = 0;
  SCI0.SCSMR.BIT.CA   = 1;
  SCI0.SCSMR.BIT.CHR  = 1;
  SCI0.SCSMR.BIT._PE  = 1;
  SCI0.SCSMR.BIT.OE   = 1;
  SCI0.SCSMR.BIT.STOP = 1;
  SCI0.SCSMR.BIT.MP   = 1;
  SCI0.SCSMR.BIT.CKS  = 3;
  SCI0.SCBRR = 0;
  SCI0.SCSCR.BYTE = 0;
  SCI0.SCSCR.BIT.TIE  = 1;
  SCI0.SCSCR.BIT.RIE  = 1;
  SCI0.SCSCR.BIT.TE   = 1;
  SCI0.SCSCR.BIT.RE   = 1;
  SCI0.SCSCR.BIT.MPIE = 1;
  SCI0.SCSCR.BIT.TEIE = 1;
  SCI0.SCSCR.BIT.CKE  = 3;
  SCI0.SCTDR = 0;
  SCI0.SCSSR.BYTE = 0;
  SCI0.SCSSR.BIT.TDRE = 1;
  SCI0.SCSSR.BIT.RDRF = 1;
  SCI0.SCSSR.BIT.ORER = 1;
  SCI0.SCSSR.BIT.FER  = 1;
  SCI0.SCSSR.BIT.PER  = 1;
  SCI0.SCSSR.BIT.TEND = 1;
  SCI0.SCSSR.BIT.MPB  = 1;
  SCI0.SCSSR.BIT.MPBT = 1;
  SCI0.SCRDR = 0;
  SCI0.SCSDCR.BYTE = 0;
  SCI0.SCSDCR.BIT.DIR = 1;
  SCI0.SCSPTR.BYTE = 0;
  SCI0.SCSPTR.BIT.EIO    = 1;
  SCI0.SCSPTR.BIT.SPB1IO = 1;
  SCI0.SCSPTR.BIT.SPB1DT = 1;
  SCI0.SCSPTR.BIT.SPB0IO = 1;
  SCI0.SCSPTR.BIT.SPB0DT = 1;
*/
}
