/***********************************************************************/
/*                                                                     */
/*  FILE        :Pacman.c                                              */
/*  DATE        :Fri, Jan 13, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7085                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
                  


void main(void) {

}
