/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Fri, Jan 13, 2017                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :SH7085                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x400
